// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm2dwfKx9xZkoe0WyhLebvSXt5P9lVWJc',
    appId: '1:1023896768906:web:6dc291369dfa6a87027873',
    messagingSenderId: '1023896768906',
    projectId: 'ecommerceapp-31ea6',
    authDomain: 'ecommerceapp-31ea6.firebaseapp.com',
    storageBucket: 'ecommerceapp-31ea6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMYxkSU79IVH4bFE06cVXdr8JWH5_uUqk',
    appId: '1:1023896768906:android:7b5dbf73d4fe1da4027873',
    messagingSenderId: '1023896768906',
    projectId: 'ecommerceapp-31ea6',
    storageBucket: 'ecommerceapp-31ea6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6i7I7ED2kPGYfTuj6LftSs8ez5H8zwBw',
    appId: '1:1023896768906:ios:eada46a3e1e98a26027873',
    messagingSenderId: '1023896768906',
    projectId: 'ecommerceapp-31ea6',
    storageBucket: 'ecommerceapp-31ea6.firebasestorage.app',
    iosBundleId: 'com.example.sStore',
  );
}
